name: CI
on:
  push:
    branches: [master, develop, renovate/**]
    paths:
      - '**'
      - '!**.md'
      - '!**.json'
  pull_request:
    branches: [master, develop, renovate/**]
    paths:
      - '**'
      - '!**.md'
      - '!**.json'
env:
  NEXT_TELEMETRY_DISABLED: 1
jobs:
  lint:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16]
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0
      - name: Setup Node ${{ matrix.node_version }} on ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Audit
        run: npm audit
      - name: Lint
        run: npm run lint
      - name: Format
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --loglevel=silent **/*.+(js|jsx|ts|tsx|json|css) --write --ignore-path .prettierignore
          only_changed: True
          same_commit: True
      #   run: npm run check:lint
      #   continue-on-error: true
      - name: Test
        # if: github.event_name == 'push' && github.ref == 'refs/heads/feat/grading-tool-ui_backend'
        run: npm test
      - name: Test components
        run: npm run test:ct
